
export const ADD_FEED = 'ADD_FEED';
export const ADD_FEED_SUCCESS = 'ADD_FEED_SUCCESS';
export const ADD_FEED_FAIL = 'ADD_FEED_FAIL';
export const FETCH_FEED_START = 'FETCH_FEED_START';
export const FETCH_FEEDS_SUCCESS = 'FETCH_FEEDS_SUCCESS';
export const FETCH_FEEDS_FAIL = 'FETCH_FEEDS_FAIL';
export const DELETE_FEED = 'DELETE_FEED';
export const DELETE_FEED_SUCCESS = 'DELETE_FEED_SUCCESS';
export const DELETE_FEED_FAIL = 'DELETE_FEED_FAIL';
export const SELECT_FEED = 'SELECT_FEED';
export const GET_FEED_LINK = 'GET_FEED_LINK';
export const GET_FEED_LINK_SUCCESS = 'GET_FEED_LINK_SUCCESS';
export const GET_FEED_LINK_FAIL = 'GET_FEED_LINK_FAIL';



